---
title: "Analysis_prediction_Scaden"
author: "Yayuan Zhu"
date: "2024-06-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 3.1 Introduction

------------------------------------------------------------------------

...

# 3.2 Libraries

------------------------------------------------------------------------

```{r}
# Libraries for data manipulation
library(tidyverse)
library(magrittr)
library(reshape2)

# Libraries for plots
library(hrbrthemes)
library(viridis)
library(ggthemes)
library(ggpubr)
extrafont::loadfonts()

# Libraries for statistical tests
library(rstatix)

# Own functions
source("functions/functions_R.R")
```

# 3.3 Data preparation

------------------------------------------------------------------------

## 3.3.1 Base dataframe of average cellular proportions

```{r}
basePattern <- "rTS_bAEblood1_c17_v"
nRandomization <- 3
nSimulations <- seq_len(10)

if(length(nRandomization) == 1) {
  path <- paste0("output/scaden_predictions/", basePattern, nRandomization, "/", basePattern, nRandomization, "_n")
  
  listLongProportions <- getLongProportions(path, nSimulations)
  avgProportions <- getAvgProportions(listLongProportions, nSimulations)
} else {
  for(i in nRandomization) {
    path <- paste0("output/scaden_predictions/", basePattern, i, "/", basePattern, i, "_n")
  
    list <- getLongProportions(path, nSimulations)
    dfAvg <- getAvgProportions(list, nSimulations) %>%
      mutate(Version = as.factor(i))
  
    assign(paste0("listLongProportions", i), list)
    assign(paste0("avgProportions", i), dfAvg)

    if(i == 1) {
      avgProportionsAll <- dfAvg
    } else {
      avgProportionsAll <- avgProportionsAll %>%
        bind_rows(dfAvg) %>%
        arrange(Patient, Celltype, Version)
    }
  }
  rm(list, dfAvg)
}
```

## 3.3.2 [Optional] Grouping epithelial sub-cell types

```{r}
epithelialCells <- c("Kidney epithelial cell", "Enterocyte", "Hepatocyte", "Pancreatic epithelial cell", "Pneumocyte")

sumEpithelial <- avgProportions %>%
  filter(Celltype %in% epithelialCells) %>%
  group_by(Patient) %>%
  summarise(`Average proportion` = sum(`Average proportion`)) %>%
  mutate(Celltype = "Epithelial cell")

avgProportions <- avgProportions %>%
  filter(!Celltype %in% epithelialCells) %>%
  bind_rows(sumEpithelial) %>%
  arrange(Patient, Celltype)
```

# 3.4 Implement patient data

------------------------------------------------------------------------

## 3.4.1 AtheroExpress

```{r}
patientData <- haven::read_sav("data/raw_data/AE_patient_data_20230803.sav")

patientData$STUDY_NUMBER <- gsub("^", "ae", patientData$STUDY_NUMBER)

patientData$Symptoms.2g <- case_when(patientData$Symptoms.4g == 0 | patientData$Symptoms.4g == 1~0,
                                     patientData$Symptoms.4g == 2 | patientData$Symptoms.4g == 3~1)

labelled::val_labels(patientData$Symptoms.2g) <- c(mild = 0, severe = 1)

patientData$thrombus.bin <- case_when(patientData$thrombus == 0 | patientData$thrombus == 1~0,
                                     patientData$thrombus == 2 | patientData$thrombus == 3~1,
                                     patientData$thrombus == -888~-888)

labelled::val_labels(patientData$thrombus.bin) <- c(`no/minor` = 0, `moderate/heavy` = 1, `not judgeable` = -888)

# The "both not present" group is not that large. Makes it easier for plotting the figure in the desired form.
patientData$smc_macrophages_ratio <- factor(patientData$smc_macrophages_ratio, levels = c(1, 3, 2))
```

```{r}
# Single average proportions data
avgPropSymp <- patientData %>%
  rename(Patient = STUDY_NUMBER) %>%
  filter(Patient %in% avgProportions$Patient) %>%
  left_join(avgProportions, by= "Patient") %>%
  select(Patient, Celltype, `Average proportion`, everything())

# List of average proportions data
# load("data/processed_data/export_files/intermediate_R_objects/rTS_bAEplaque_c7-13-17.RData")
# 
# listAvgProp <- c("avgProp_c7_v1", "avgProp_c13_v1", "avgProp_c17_v1")
# 
# for(data in listAvgProp) {
#   name <- paste0("avgPropSymp", str_extract(data, "_c\\d+_v\\d+"))
#   
#   avgPropSymp <- patientData %>%
#     rename(Patient = STUDY_NUMBER) %>%
#     filter(Patient %in% get(data)$Patient) %>%
#     left_join(get(data), by= "Patient") %>%
#     select(Patient, Celltype, `Average proportion`, everything())
#   
#   assign(name, avgPropSymp)
# }
# 
# rm(avgPropSymp)
```

# 3.5 Statistics

------------------------------------------------------------------------

## 3.5.1 Test assumptions

```{r}
# Test for normality
resShapiro <- avgPropSymp %>%
  group_by(Celltype) %>%
  summarise(pvalue = shapiro_test(`Average proportion`)$p.value) %>%
  add_significance("pvalue")

for(celltype in unique(avgPropSymp$Celltype)) {
  subset <- avgPropSymp %>%
    filter(Celltype == celltype)

  qqp <- ggpubr::ggqqplot(subset$`Average proportion`) +
    labs(title = paste("Q-Q plot for", celltype))

  print(qqp)
}

# Test for homogeneity of variance
resLevene <- avgPropSymp %>%
  levene_test(`Average proportion` ~ Celltype)
```

## 3.5.2 Differences between patient groups within each cell type

```{r}
charStats <- c("Symptoms.2g", "Symptoms.4g", "Gender", "Macrophages.bin", "SMC.bin", "IPH.bin", "smc_macrophages_ratio", "plaquephenotype")

orderedCelltypes <- avgPropSymp %>%
  group_by(Celltype) %>%
  summarise(`Average proportion` = mean(`Average proportion`)) %>%
  arrange(`Average proportion`) %>%
  pull(Celltype)

avgPropSymp$Celltype <- factor(avgPropSymp$Celltype, levels = orderedCelltypes)

filteredSympStats <- sympFilter(avgPropSymp, charStats)

resStats <- list()
resDunnList <- list()

for(symp in names(filteredSympStats)) {
  df <- filteredSympStats[[symp]] %>%
    rename(avgProp = `Average proportion`)
  
  formula <- as.formula(paste("avgProp", symp, sep = "~"))

  if(n_distinct(df[[symp]]) > 2) {
    res <- df %>%
      group_by(Celltype) %>%
      kruskal_test(formula = formula) %>%
      add_significance("p")
    
    resDunn <- df %>%
      group_by(Celltype) %>%
      dunn_test(formula = formula, p.adjust.method = "none") %>%
      add_significance("p") %>%
      add_xy_position(x = "Celltype")
    
    resDunnList[[symp]] <- resDunn
  } else {
    res <- df %>%
      group_by(Celltype) %>%
      wilcox_test(formula = formula) %>% 
      add_significance("p") %>%
      add_xy_position(x = "Celltype")
  }
  resStats[[symp]] <- res
}
```

# 3.6 Graphs

------------------------------------------------------------------------

## 3.6.1 All cellular proportions

```{r}
pattern <- "rTS_bAEblood1_c17_v3"
nCelltypes <- "17"
nSimulations <- seq_len(10)

pdf(paste0("output/pdf/", pattern, "_all_graphs.pdf"))

for(n in nSimulations) {
  p <- ggplot(listLongProportions[[paste0("longPred", n)]], aes(x = Celltype, y = Proportion)) +
    geom_boxplot(fill = "lightgrey") +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1),
                       breaks = seq(0, 1, by = 0.1)) +
    labs(title = paste0("Cellular deconvolution predictions: ", pattern),
         subtitle = paste("Celltypes:", nCelltypes,
                          "\nRun:", n)) +
    ylab("Relative average proportion") +
    xlab("Cell type") +
    ownTheme()

  print(p)
}

dev.off()
```

## 3.6.2 Average cellular proportion

### 3.6.2.1 One version

```{r}
pattern <- "rTS_bAEblood1_c17_v3"
nCelltypes <- "17"
nSimulations <- seq_len(10)

pAvg <- ggplot(avgProportions, aes(x = reorder(Celltype, `Average proportion`), y = (`Average proportion`))) +
  geom_boxplot(fill = "lightgrey") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1),
                     breaks = seq(0, 1, by = 0.1)) +
  labs(title = paste0("Cellular deconvolution average prediction: ", pattern),
       subtitle = paste("Cell types:", nCelltypes,
                        "\nTotal runs:", length(nSimulations))) +
  ylab("Relative average proportion") +
  xlab("Cell type") +
  theme_ipsum_rc(grid = "Y") +
  ownTheme()

tiff(paste0("output/plots/average_predictions_plots/", pattern, "_avg_pred.tiff"),
     width = 10, height = 10, units = "in", res = 300)

print(pAvg)

dev.off()
```

### 3.6.2.2 Groups

```{r}
# Optional for pilot ccfRNA deconvolution: add which cells correspond to which blood tissue fraction
bloodMetadata <- read_delim("data/metadata/cfRNA_blood_pilot_annotation.txt") %>%
  rename("Patient" = "ID")

bloodMetadata$tissue <- as.factor(bloodMetadata$tissue)

avgProportions %<>%
  left_join(bloodMetadata, by = "Patient")
```

```{r}
pattern <- "rTS_bAEplaque_c13_v1-3"
nCelltypes <- "13"

pGroup <- fillBoxplot(data = avgProportionsAll,
                      pattern = pattern,
                      col = "Version",
                      nCelltypes = nCelltypes,
                      legendName = "Randomization",
                      labels = NULL)

tiff(paste0("output/plots/average_predictions_plots/", pattern, "_avg_prediction.tiff"), 
     width = 12, height = 8, units = "in", res = 300)

print(pGroup)

dev.off()
```

### 3.6.2.3 AtheroExpress patient characteristics

```{r}
pattern <- "rTS_bAEblood1_c17_v3"
nCelltypes <- "17"

listChar <- list(
  list(col = "Symptoms.2g", labels = c("mild", "severe")),
  list(col = "Symptoms.4g", labels = c("asymptomatic", "ocular", "tia", "stroke")),
  list(col = "Gender", labels = c("female", "male")),
  list(col = "Macrophages.bin", labels = c("no/minor", "moderate/heavy")),
  list(col = "SMC.bin", labels = c("no/minor", "moderate/heavy")),
  list(col = "IPH.bin", labels = c("no", "yes")),
  list(col = "smc_macrophages_ratio", labels = c("smc dominant", "equal", "macrophages dominant")),
  list(col = "plaquephenotype", labels = c("fibrous", "fibroatheromatous", "atheromatous"))
)

toFilter <- sapply(listChar, function(x) x$col)

filteredSympData <- sympFilter(avgPropSymp, toFilter)

plotList <- list()
plotListPDF <- list()

for(char in listChar) {
  col <- char$col
  labels <- char$labels
  
  pChar <- fillBoxplot(data = filteredSympData[[col]],
                       pattern = pattern,
                       col = col,
                       nCelltypes = nCelltypes,
                       labels = labels)
  
  pPDF <- fillBoxplotPDF(data = filteredSympData[[col]],
                         pattern = pattern,
                         col = col,
                         nCelltypes = nCelltypes,
                         labels = labels)
  
  plotList[[col]] = pChar
  plotListPDF[[col]] = pPDF
}
```

```{r}
# Exporting plots without significance bars
for(name in names(plotList)) {
  tiff(paste0("output/plots/average_predictions_plots/patient_symptoms/no_significance_sign/", pattern, "_", name, ".tiff"),
       width = 12, height = 8, units = "in", res = 300)
  
  print(plotList[[name]])
  
  dev.off()
}

pdf(paste0("output/pdf/", pattern, "_patient_symptoms.pdf"))

for(name in names(plotListPDF)) {
  print(plotListPDF[[name]])
}

dev.off()
```

```{r}
signPlotList <- list()
signPlotListPDF <- list()

for(symp in names(resStats)) {
  if(symp %in% names(resDunnList)) {
    df <- resDunnList[[symp]]
  } else {
    df <- resStats[[symp]]
  }
  
  pAdd <- plotList[[symp]]
  pAddPDF <- plotListPDF[[symp]]
    
  pSign <- pAdd +
    stat_pvalue_manual(df, label = "p.signif", hide.ns = TRUE, tip.length = 0.5)
  pSignPDF <- pAddPDF +
    stat_pvalue_manual(df, label = "p.signif", hide.ns = TRUE, tip.length = 0.5)

  signPlotList[[symp]] <- pSign
  signPlotListPDF[[symp]] <- pSignPDF
}
```

```{r}
# Exporting plots with significance bars
pattern <- "rTS_bAEblood1_c17_v3"

for(name in names(signPlotList)) {
  tiff(paste0("output/plots/average_predictions_plots/patient_symptoms/significance_sign/", pattern, "_", name, "_not_adj.tiff"),
       width = 12, height = 8, units = "in", res = 300)
  
  print(signPlotList[[name]])
  
  dev.off()
}

pdf(paste0("output/pdf/", pattern, "_patient_symptoms_sign.pdf"))

for(name in names(signPlotListPDF)) {
  print(signPlotListPDF[[name]])
}

dev.off()
```

## 3.6.3 Correlation

### 3.6.3.1 Data preparation

```{r}
listLongProportionsPlaque <- getLongProportions("output/scaden_predictions/rAEplaque_bAEplaque_c7_v1/rAEplaque_bAEplaque_c7_v1_n", 
                                                nSimulations = seq_len(10))

avgProportionsPlaque <- getAvgProportions(listLongProportionsPlaque,
                                          nSimulations = seq_len(10))

# Dataframe for scatter plots
listCellTypes <- unique(avgProportions$Celltype)

combine <- avgProportionsPlaque %>%
  rename(`Average proportion Plaque` = `Average proportion`)

for(cellType in listCellTypes) {
  avgPropName <- paste("Average proportion", cellType)
  
  col <- avgProportions %>%
    filter(Celltype == cellType) %>%
    rename(!!avgPropName := `Average proportion`) %>%
    select(-Celltype)
  
  combine <- combine %>%
    left_join(col, by = "Patient")
}

plotNamesCellTypes <- listCellTypes %>%
  str_replace_all(c(" " = "_",
                    "/" = "_"))

colnames(combine) <- colnames(combine) %>%
  str_replace_all(c(" " = "_",
                    "/" = "_"))

# Dataframe for heatmap
corAEplaqueTS <- combine %>%
  group_by(Celltype) %>%
  summarise(across(starts_with("Average_proportion_"), 
                   ~ cor(.x, Average_proportion_Plaque), .names = "cor_{col}")) %>%
  column_to_rownames("Celltype") %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column("TS_cell_type") %>%
  pivot_longer(cols = -TS_cell_type, names_to = "AE_plaque_cell_type", values_to = "Correlation") %>%
  mutate(TS_cell_type = gsub("cor_Average_proportion_", "", TS_cell_type))

corLevels <- unique(corAEplaqueTS$TS_cell_type)
corLevels <- corLevels[corLevels != "Plaque"]

orderLevels <- c(rev(corLevels), "", "Plaque")

dummy <- data.frame(TS_cell_type = rep("", 7),
                    AE_plaque_cell_type = unique(corAEplaqueTS$AE_plaque_cell_type),
                    Correlation = NA)

corAEplaqueTS <- rbind(corAEplaqueTS[1:7,], dummy, corAEplaqueTS[8:nrow(corAEplaqueTS),])

corAEplaqueTS$TS_cell_type <- factor(corAEplaqueTS$TS_cell_type, 
                                     levels = orderLevels)
```

### 3.6.3.2 Scatter plot

```{r}
pattern <- "rTS_bAEplaque_c17_v1"

for(i in (4:ncol(combine))) {
  colName <- colnames(combine)[i]
  
  tiff(paste0("output/plots/correlation_plots/", pattern, "/cor_", plotNamesCellTypes[i-3], "_", pattern, ".tiff"),
       width = 12,
       height = 8,
       units ="in",
       res = 300)
  
  p <- ggplot(combine, aes(x = .data[[colName]], y = Average_proportion_Plaque)) +
    geom_point() +
    geom_smooth(method = lm) +
    facet_wrap(~ Celltype,
               nrow = 3,
               scales = "free") +
    labs(title = paste("Correlation average predicted cellular proportions", pattern),
           subtitle = paste("Comparison: AE plaque versus Tabula Sapiens", plotNamesCellTypes[i-3])) +
    theme_ipsum_rc(grid="Y") +
  ownTheme()
  
  print(p)
  
  dev.off()
}
```

### 3.6.3.3 Heat map

```{r}
pattern <- "rTS_bAEplaque_c10_v1"

tiff(paste0("output/plots/correlation_plots/", pattern, "_heatmap.tiff"),
     width = 12,
     height = 12,
     units = "in",
     res = 300)

ggplot(corAEplaqueTS, aes(x = AE_plaque_cell_type, y = TS_cell_type)) +
  geom_tile(aes(fill = Correlation),
            color = "white") +
  scale_fill_distiller(palette = "RdBu",
                       limit = c(-1, 1),
                       na.value="white") +
  labs(title = "Correlation of average cellular proportions of AtheroExpress bulk RNA-seq data\nbetween Tabula Sapiens and AtheroExpress plaque references",
       subtitle = pattern,
       x = "AtheroExpress plaque reference",
       y = "Tabula Sapiens reference") +
  theme_ipsum_rc(grid = FALSE) +
  ownTheme()

dev.off()
```

# 3.7 Session info

```{r}
devtools::session_info()
```
