---
title: "Deconvolution_BayesPrism"
author: "Yayuan Zhu"
date: "2024-02-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

```{r message=FALSE, warning=FALSE}
library(magrittr)
library(tidyverse)
library(BayesPrism)

```

## Quality control scRNA dataset

```{r}
scData <- subset(read_rds("input/full.43p_10X.integrated.cleaned.archetypes.seurat.RDS"), Tissue != "PBMC")
```

```{r}
scData@meta.data$log10GenesPerUMI <- log10(scData$nFeature_RNA) / log10(scData$nCount_RNA)

scData$mitoRatio <- PercentageFeatureSet(object = scData, pattern = "^MT-")
scData$mitoRatio <- scData@meta.data$mitoRatio / 100

metadata <- scData@meta.data

metadata <- metadata %>%
        dplyr::rename(seq_folder = orig.ident,
                      nUMI = nCount_RNA,
                      nGene = nFeature_RNA)

metadata %>% 
  	ggplot(aes(x=nUMI)) + 
  	geom_density() + 
  	scale_x_log10() + 
  	theme_classic() +
  	ylab("Cell density") +
  	geom_vline(xintercept = 500)

metadata %>% 
  	ggplot(aes(x=nGene)) + 
  	geom_density(alpha = 0.2) + 
  	theme_classic() +
  	scale_x_log10() + 
  	geom_vline(xintercept = 300)

metadata %>% 
  	ggplot(aes(x=nUMI, y=nGene, color=mitoRatio)) + 
  	geom_point() + 
	scale_colour_gradient(low = "gray90", high = "black") +
  	stat_smooth(method=lm) +
  	scale_x_log10() + 
  	scale_y_log10() + 
  	theme_classic() +
  	geom_vline(xintercept = 500) +
  	geom_hline(yintercept = 250)

metadata %>% 
  	ggplot(aes(x=mitoRatio)) + 
  	geom_density(alpha = 0.2) + 
  	scale_x_log10() + 
  	theme_classic() +
  	geom_vline(xintercept = 0.2)

metadata %>%
  	ggplot(aes(x=log10GenesPerUMI)) +
  	geom_density(alpha = 0.2) +
  	theme_classic() +
  	geom_vline(xintercept = 0.8)
```
