---
title: "Deconvolution Scaden"
author: "Yayuan Zhu"
date: "2024-01-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

Creating pseudo bulk mixtures for training of the algorithm and performing the deconvolution.

### Setup

```{r message=FALSE, warning=FALSE}
library(magrittr)
library(tidyverse)
```

## Deconvolution with Scaden

### Example datasets

```{r}
exampleBulk <- read.table("example_data/example_bulk_data.txt")
exampleCellTypes <- read.table("example_data/example_celltypes.txt")
exampleCounts <- read_table("example_data/example_counts.txt")
```

```{bash}
scaden simulate --data example_data/ -n 100 --pattern "*_counts.txt"

scaden process data.h5ad example_data/example_bulk_data.txt --processed_path example_data/processed.h5ad

scaden train processed.h5ad --steps 5000 --model_dir model

scaden predict --model_dir model example_data/example_bulk_data.txt
```

```{bash}
dirPath="example_data/"

scaden simulate --data $dirPath -n 10 --pattern "*_counts.txt"
```

### AtheroExpress data

```{r}
scadenBulk <- read.delim("output/scaden_format_files/scaden_bulk_data.txt")
scadenCellTypes <- read.delim("output/scaden_format_files/scaden_celltypes.txt")
scadenCounts <- read.delim("output/scaden_format_files/scaden_counts.txt")

19:24
```

]TEST

```{bash}
bk="800"

dirPathOutput="output/scaden_simulations_plaque/scaden_plaque_b$bk/plaque_b${bk}_"

dirPathModel="models/scaden_models_plaque/model_plaque_b${bk}_"

for i in {1..2}
do
  mv $i.txt ${dirPathOutput}${i}
done
```

```{bash}
source functions/functions_bash.sh

bk="test"
createDir "output/scaden_simulations_plaque/scaden_plaque_b$bk"
```

#### 800 bulk samples

```{bash}
source functions/functions_bash.sh
set -e

bk="10" #Number of bulk RNA-seq samples to be simulated.

dirPathOutput="output/scaden_simulations_plaque/scaden_plaque_b$bk/plaque_b${bk}_"
dirPathModel="models/scaden_models_plaque/scaden_models_plaque_b$bk/model_plaque_b${bk}_"
dirPathPred="output/scaden_simulations_plaque/scaden_plaque_b$bk/predictions"

createDir "output/scaden_simulations_plaque/scaden_plaque_b$bk"
createDir "models/scaden_models_plaque/scaden_models_plaque_b$bk"
createDir "output/scaden_simulations_plaque/scaden_plaque_b$bk/predictions"

for i in {14..15}
do
  mkdir ${dirPathOutput}${i}
  
  scaden simulate --data output/scaden_format_files/ -n $bk --pattern "*_counts.txt" --out ${dirPathOutput}${i}
  
  scaden process ${dirPathOutput}${i}/scaden.h5ad output/scaden_format_files/scaden_bulk_data.txt --processed_path ${dirPathOutput}${i}/processed.h5ad
  
  mkdir ${dirPathModel}${i}
  
  scaden train ${dirPathOutput}${i}/processed.h5ad --steps 50 --model_dir ${dirPathModel}${i}
  
  scaden predict --model_dir ${dirPathModel}${i} output/scaden_format_files/scaden_bulk_data.txt --outname predictions_plaque_b${bk}_${i}
  
  mv predictions_plaque_b${bk}_${i} ${dirPathPred}
done
```

```{bash}
shutdown now
```

## Plotting predictions

### Example prediction

```{r}
examplePrediction <- read.table("example_data/example_predictions.txt")

longExample <- examplePrediction %>%
  rownames_to_column("Sample") %>%
  pivot_longer(
             cols = -Sample,
             names_to = "Celltype",
             values_to = "Proportion"
  )

ggplot(longExample, aes(x = Celltype, y = Proportion)) +
  geom_boxplot()
```

### AtheroExpress data (rownames excluded)

```{r}
scadenBulk <- read.delim("output/scaden_format_files/scaden_bulk_data.txt")
scadenCounts <- read.delim("output/scaden_format_files/scaden_counts.txt")
scadenCellTypes <- read.delim("output/scaden_format_files/scaden_celltypes.txt")

View(as.data.frame(head(scadenCounts)))

scadenPred1 <- read.delim("scaden_predictions.txt", check.names = FALSE)
colnames(scadenPred1)[1] = "Patient"

cellTypes <- colnames(scadenPred1)[2:ncol(scadenPred1)]

newNames <- as.vector(c("Class-switched Memory B Cells",
                        "Smooth Muscle Cells",
                        "Endothelial Cells",
                        "FOXP3+ T Cells",
                        "CD56- NK Cells",
                        "CD56+ NK Cells",
                        "Proliferating T Cells",
                        "Resident-like Macrophages",
                        "CD4+ T Cells",
                        "Lipid Associated Macrophages",
                        "Inflammatory Lipid Associated Macrophages",
                        "CD8+ T Cells",
                        "Inflammatory Foamy Macrophages",
                        "cDC2",
                        "Inflammatory Monocyte-derived Macrophages",
                        "Foamy Macrophages",
                        "S100A8+ Migrating Monocyte-derived Macrophages",
                        "Antigen-presenting Monocyte-derived Macrophages",
                        "cDC1",
                        "Mast Cells",
                        "CD16+ Migrating Monocyte-derived Macrophages"))

renamedCellTypes <- as.data.frame(cbind(cellTypes, newNames))

colnames(scadenPred1)[2:ncol(scadenPred1)] <- newNames

longScadenPred1 <- scadenPred1 %>%
  pivot_longer(
    cols = -Patient,
    names_to = "Celltype",
    values_to = "Proportion"
  )

ggplot(longScadenPred1, aes(x = Celltype, y = Proportion)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle=60, vjust = 1, hjust = 1, size = 8))
```

### Iterative

```{r}
for (i in 1:10){
  print(i)
}

for(i in 1:10){
  filePath <- paste("output/plaque_b700_", i, "/predictions_plaque_b700_", i, ".txt", sep = "")
  fileName <- paste("predictions", i, sep = "")
  
  fileName <- read.delim(file_path)
  colnames(fileName)[1] = "Patient"
}

cellTypes <- colnames(fileName)[2:ncol(fileName)]

newNames <- as.vector(c("Class-switched Memory B Cells",
                        "Smooth Muscle Cells",
                        "Endothelial Cells",
                        "FOXP3+ T Cells",
                        "CD56- NK Cells",
                        "CD56+ NK Cells",
                        "Proliferating T Cells",
                        "Resident-like Macrophages",
                        "CD4+ T Cells",
                        "Lipid Associated Macrophages",
                        "Inflammatory Lipid Associated Macrophages",
                        "CD8+ T Cells",
                        "Inflammatory Foamy Macrophages",
                        "cDC2",
                        "Inflammatory Monocyte-derived Macrophages",
                        "Foamy Macrophages",
                        "S100A8+ Migrating Monocyte-derived Macrophages",
                        "Antigen-presenting Monocyte-derived Macrophages",
                        "cDC1",
                        "Mast Cells",
                        "CD16+ Migrating Monocyte-derived Macrophages"))

renamedCellTypes <- as.data.frame(cbind(cellTypes, newNames))

for(i in 1:10){
  fileName <- paste("predictions", i, sep = "")
  
  colnames(fileName)[2:ncol(fileName)] <- newNames
  
  longName <- paste("longPredictions", i)
  
  longName <- fileName %>%
    pivot_longer(
      cols = -Patient,
      names_to = "Celltype",
      values_to = "Cell type proportion"
    )
  
  ggplot(longName, aes(x = Celltype, y = Proportion)) +
    geom_boxplot() +
    theme(axis.text.x = element_text(angle=60, vjust = 1, hjust = 1, size = 8))
  
  ggsave(paste(fileName, ".png", sep = ""))
  
}
```

## Session info

```{r}
devtools::session_info()
```
